### ISSUE TITLE
Custom-json parser doesn't handle json arrays

### ISSUE THREAD

**Issue by sklirg** [telenornms/skogul#132]
The custom-json parser only handles json objects, not json arrays. This is most likely due to the strict `map[string]interface{}`, which requires key/value-pairs, and does not support arrays.

If the incoming json to `custom-json` parser is on the form of 
```json
[
  {
    "foo": "bar"
  }
]
```
the custom-json parser will error with "could not parse".

I think arrays should be supported.

**Comment by moogacs** [comment]
By you `map[string]interface{}` i assume you mean what is inside [parser/json.go](https://github.com/telenornms/skogul/blob/1d8fa60584c5acb117c239e4088ec99c50f013d2/parser/json.go#L55) with test transformer/[timestamp_test.go](https://github.com/telenornms/skogul/blob/1d8fa60584c5acb117c239e4088ec99c50f013d2/transformer/timestamp_test.go#L47)

**Comment by KristianLyng** [comment]
Almost. The make() there is for the metadata, which is just an empty map[string]interface{} prior to any transformer filling in data. It's created in the parser because having nil-value metadata is a bit of a headache.

The real issue is https://github.com/telenornms/skogul/blob/5fbb2d6c18666420d3a60d6685b87279e98a0a81/parser/json.go#L59 where the unmarshal onto Data happens, since Data is a map[string]interface{} (Unmarshal will create it when it has a nil-value).

We don't want to change the Container defintion, so changing Data to be `interface{}` instead of `map[string]interface{}` isn't really an option.

What we could do in this case is a two-phase attempt. If the initial Unmarshal fail because the data is an array, we could create a `var foo interface{}`, Unmarshal onto that, then set up `Data["blob"] = foo`.

It would give an extra level of nesting, but I think that's reasonable in these situations. This would also mean that single-value data could be parsed, like just a single number, hence "blob" instead of "array".

My only real reservation is the extra attempt required... But I don't see any other obvious way.

**Comment by KristianLyng** [comment]
This is fixed by #156
