### ISSUE TITLE
Migrate docker image building to Github Actions

### ISSUE THREAD

**Issue by KristianLyng** [telenornms/skogul#273]
After drone apparently just decided to never work again, we're moving to Github actions.

Need to move the docker image building.

**Comment by sklirg** [comment]
I accidentally pushed some commits to primary in this repo instead of primary in my fork, but you can verify my fork for the work done and the added action.

Steps maybe needed by you (@KristianLyng) with admin perms:

* Go to here: https://github.com/telenornms/skogul/pkgs/container/skogul
    * Click Package Settings
    * Verify that "Actions" has write permissions[0] (This might have to be done through the organization page somehow ("telenornms"), as you can see from the attached screenshot[0] I did it on my "personal profile")

I took the liberty to test a build on tag release in this repo as well, which ended up with:
> Error: buildx failed with: ERROR: denied: permission_denied: write_package

* https://github.com/telenornms/skogul/actions/runs/3472955590/jobs/5804425446


[0]:
![image](https://user-images.githubusercontent.com/5422571/201992406-79ff1123-589d-453c-889a-e3c52a55acbe.png)

**Comment by sklirg** [comment]
Fixed!
